volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pifourni/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pifourni/data/mariadb

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build: ./srcs/requirements/nginx/.
    image: nginx:1.0
    ports:
     - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
     - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - ./srcs/.env
    restart: always
  wordpress:
    container_name: wordpress
    build: ./srcs/requirements/wordpress/.
    image: wordpress:1.0
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - ./srcs/.env
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "php -r '$$socket = @fsockopen(\"127.0.0.1\", 9000); exit($$socket ? 0 : 1);'"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
  mariadb:
    container_name: mariadb
    build: ./srcs/requirements/mariadb/.
    image: mariadb:1.0
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - ./srcs/.env
    networks:
      - inception
    restart: always