services:
  mariadb:
    build:
      context: ./srcs/requirements
      dockerfile: mariadb/Dockerfile
    container_name: mariadb
    env_file:
      - ./srcs/.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    build:
      context: ./srcs/requirements
      dockerfile: wordpress/Dockerfile
    container_name: wordpress
    env_file:
      - ./srcs/.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_HOST}
    secrets:
      - db_password
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  mariadb_data:

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt