FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
	php-fpm php-mysql php-curl php-gd php-mbstring php-xml php-zip \
	curl mariadb-client wget tar less \
	&& rm -rf /var/lib§apt/lists/*

WORKDIR /var/www/html

COPY conf/www.conf /etc/php/8.2/fpm/pool.d/www.conf
COPY tools/wp-setup.sh /usr/local/bin/wp-setup.sh
RUN chmod +x /usr/local/bin/wp-setup.sh

EXPOSE 9000
ENTRYPOINT ["/usr/local/bin/wp-setup.sh"]
